<?php

return [
    'Lead' => [
        "First_Name"        => 'first_name',
        "Last_Name"         => 'last_name',
        "Email"             => 'email',
        "Phone"             => 'phone',
        "Alt_Phone"         => 'alt_phone',
        "Address"           => 'address',
        "City"              => 'city',
        "State"             => 'state',
        "Postal"            => 'postal',
        "Country"           => 'country',
        "IP"                => 'ip',
        "Date_Subscribed"   => 'date_subscribed',
        "Gender"            => 'gender',
        "Offer_URL"         => 'offer_url',
        "DOB"               => 'dob',
        "List_ID"           => 'list_id',
        "Import_Date"       => 'import_date',
        "Phone_Type"        => 'phone_type',
        "Tax_Debt_Amount"   => 'tax_debt_amount',
        "CC_Debt_Amount"    => 'cc_debt_amount',
        "Type_Of_Debt"      => 'type_of_debt',
        "Homeowner"         => 'home_owner',
        "Jornaya_ID"        => 'jornaya_id',
        "Trusted_Form_ID"   => 'trusted_form_id',
        "Opt_In"            => 'opt_in',
        "SubID1"            => 'sub_id_1',
        "SubID2"            => 'sub_id_2',
        "SubID3"            => 'sub_id_3',
        "SubID4"            => 'sub_id_4',
        "SubID5"            => 'sub_id_5',
        "Aff_ID_1"          => 'aff_id_1',
        "Aff_ID_2"          => 'aff_id_2',
        "Lead_ID"           => 'lead_id',
        "Page_URL"          => 'page_url',
        "EF_ID"             => 'ef_id',
        "CK_ID"             => 'ck_id',
    ],
];
